services:
  backend:
    build: ./backend
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
      - ./config.txt:/app/config.txt
    entrypoint: /usr/local/bin/backend /app/config.txt
  bot:
    build: ./discord-bot
    restart: unless-stopped
    volumes:
      - ./config.txt:/app/config.txt
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=lurky
      - POSTGRES_PASSWORD=put_a_good_password_here
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local